// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysdykrsifyedlzienuvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZHlrcnNpZnllZGx6aWVudXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTc0MzIsImV4cCI6MjA2MzU5MzQzMn0.DGo-SuymCr91YUnd6viPmsh7Ug8Fb3AevtLGWRBUn-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);